javac -d . tensor.java
javac -d . add.java
javac -d . sub.java
javac -d . div.java
javac -d . mul.java
javac -d . exp.java
javac -d . log.java
javac -d . negate.java
javac -d . tensorarray.java
javac -d . tensorarray3d.java
javac -d . superopdef.java
javac -d . backpropagationstructure.java
javac -d . tensorgraph.java
javac -d . add_tensorarray.java
javac -d . sub_tensorarray.java
javac -d . mul_tensorarray.java
javac -d . mul_tensorarray3d.java
javac -d . tensorarrayops.java
javac -d . dot3d.java
javac -d . reduce_sum.java
javac -d . reduce_sum3d.java
javac -d . div_tensorarray.java
javac -d . exp_tensorarray.java
javac -d . negate_tensorarray.java
javac -d . sigmoid.java
javac -d . reduce_sum.java
javac -d . dot.java
javac -d . convolution.java
